workflow:
  rules:
    - if: '$START == "true"'
      when: always
    - when: never
    
stages:
  - pre-build

build:functions:
  before_script:
    - npm i -g zcatalyst-cli
  stage: build
  script:
    - catalyst deploy --project $CATALYST_PROJECT_NAME --org $CATALYST_ORG --token $CATALYST_TOKEN
build:release:
  stage: build
  needs: ["build:functions"]
  script:
    - zip -r release.zip .
  artifacts:
    expire_in: 30 mins
    paths:
      - ./release.zip




 

